### ISSUE TITLE
About the clustering loss 

### ISSUE THREAD

**Issue by 1173206772** [facebookresearch/deepcluster#83] opened 2021-04-15 15:13 UTC
During my training, the clustering loss did not drop(remain the same),while the loss of CNN remained decreased .
I don't know whether this result is correct, and whether the clustering loss will decrease during training.
And since the clustering results are used as pseudo-labels to train the network, does it mean that the best results of the trained network can only achieve the effect of the clustering algorithm? 
I hope you can answer my questions, very grateful ！！

**Comment by mathildecaron31** [comment] 2021-04-30 11:27
Duplicate of https://github.com/facebookresearch/deepcluster/issues/84

**Closed as completed by mathildecaron31** 2021-04-30 11:27 UTC
